Script now builds APK

diff --git a/itch-assemble-and-upload b/itch-assemble-and-upload
--- a/itch-assemble-and-upload
+++ b/itch-assemble-and-upload
@@ -5,12 +5,6 @@ if [ $# -eq 0 ]; then
     exit 1
 fi
 
-if [ "$1" != "$(jq '.elements[0].versionName' --raw-output \
-	< app/build/outputs/apk/itchio/release/output-metadata.json)" ]; then
-    echo "Error: version number does not match metadata!"
-    exit 1
-fi
-
 if [ "$(git status --porcelain | wc --lines)" -ne 0 ]; then
     echo "Error: uncommited changes!"
     exit 1
@@ -18,6 +12,14 @@ fi
 
 if [ "$(git rev-parse main)" != "$(git rev-parse origin/main)" ]; then
     echo "Error: main branch not sync with origin/main!"
+    exit 1
+fi
+
+./gradlew assembleItchioRelease
+
+if [ "$1" != "$(jq '.elements[0].versionName' --raw-output \
+	< app/build/outputs/apk/itchio/release/output-metadata.json)" ]; then
+    echo "Error: version number does not match metadata!"
     exit 1
 fi
 
