itch-upload: check metadata before uploading

diff --git a/itch-upload b/itch-upload
--- a/itch-upload
+++ b/itch-upload
@@ -5,6 +5,12 @@ if [ $# -eq 0 ]; then
     exit 1
 fi
 
+if [ "$1" != "$(jq '.elements[0].versionName' --raw-output \
+	< app/build/outputs/apk/itchio/release/output-metadata.json)" ]; then
+    echo "Error: version number does not match metadata!"
+    exit 1
+fi
+
 if [ "$(git status --porcelain | wc --lines)" -ne 0 ]; then
     echo "Error: uncommited changes!"
     exit 1
@@ -15,4 +21,4 @@ if [ "$(git rev-parse main)" != "$(git rev-parse origin/main)" ]; then
     exit 1
 fi
 
-butler push app/build/outputs/apk/itchio/release/app-itchio-release.apk gardenapple/mitch:android --userversion $1
+butler push app/build/outputs/apk/itchio/release/app-itchio-release.apk gardenapple/mitch:android --userversion "$1"
