Experiment with itch-upload script

diff --git a/itch-upload b/itch-upload
--- a/itch-upload
+++ b/itch-upload
@@ -2,7 +2,17 @@
 
 if [ $# -eq 0 ]; then
     echo "Supply version number (such as 1.0.1)"
-    exit
+    exit 1
 fi
 
-butler push build-release/itchio/release/app-itchio-release.apk gardenapple/mitch:android --userversion $1
+if [ "$(git status --porcelain | wc --lines)" -ne 0 ]; then
+    echo "Error: uncommited changes!"
+    exit 1
+fi
+
+if [ "$(git rev-parse main)" -ne "$(git rev-parse origin/main" ]; then
+    echo "Error: main branch not sync with origin/main!"
+    exit 1
+fi
+
+#butler push build-release/itchio/release/app-itchio-release.apk gardenapple/mitch:android --userversion $1
